# Generated by Django 5.1 on 2024-09-07 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercios', '0002_remove_cliente_direccion_cliente_domicilio'),
    ]

    operations = [
        migrations.AddField(
            model_name='ropa',
            name='tipo',
            field=models.CharField(choices=[('remera', 'Remera'), ('pantalon', 'Pantalon'), ('campera', 'Campera')], default='remera', max_length=10),
        ),
        migrations.AlterField(
            model_name='ropa',
            name='talle',
            field=models.TextField(blank=True, max_length=25, null=True),
        ),
    ]
