# Generated by Django 5.1 on 2024-09-07 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comercios', '0003_ropa_tipo_alter_ropa_talle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='ropa',
            options={'verbose_name': 'Ropa', 'verbose_name_plural': 'Ropa'},
        ),
        migrations.AlterModelOptions(
            name='ventas',
            options={'verbose_name': 'venta', 'verbose_name_plural': 'Ventas'},
        ),
    ]
