# Generated by Django 5.1 on 2024-09-07 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercios', '0005_alter_ventas_estado_talle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talle',
            name='talle',
            field=models.CharField(choices=[('s', 'S'), ('m', 'M'), ('l', 'L'), ('xl', 'XL'), ('xxl', 'XXL')], max_length=3),
        ),
    ]
