# Generated by Django 5.1.1 on 2024-09-14 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercios', '0007_remove_ropa_stock_remove_ropa_talle'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
