# Generated by Django 5.1.1 on 2024-09-14 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercios', '0008_cliente_nacimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventas',
            name='cliente_nombre',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
